import Head from "next/head";
import Image from "next/image";
import Navbar from "../../components/navbar";
import HomeHeader from "../../components/headers/homeHeader";
import ServerCard from "../../components/ServerCard";

function ServerList({
  serverlist_options,
}) {
  return (
    <>
      <Head>
        <title>ARK Classic - Servers</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
          integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <div class="flex min-h-screen items-center justify-center p-20">
        <div className="flex w-full space-x-6">
          <div
		class="p-4 w-1/4 flex-none shadow-md sm:p-8 bg-gray-300 dark:bg-bgray-secondary rounded-3xl">
		<h3 class="mb-2 text-3xl font-bold text-gray-800 dark:text-white text-center ">Having trouble joining?</h3>
		<p class="mb-5 text-base text-gray-600 dark:text-gray-100 sm:text-lg text-center ">We can help you! Follow this simple step-by-step guide to get started.
    </p>
    <p class="mb-5 text-base text-gray-600 dark:text-gray-400 sm:text-lg text-left">
    <br/>
      Instructions for Steam are as follows:   <br/>
      Step 1: Open the Steam client.   <br/>
      Step 2: At the top left, click on View.   <br/>
      Step 3: Click on Servers and head over to the Favorites tab.   <br/>
      Step 4: Click Add Server to Favorites.   <br/>
      Step 5: Enter following Server IP below then click add this address to favorit   <br/>
      Step 6: Start Ark Survival and click Join ARK   <br/>
      Step 7: Filter for favorites and ensure all other filters are reset   <br/>
      <br/>
      The server should now visible for you   <br/>
      <br/>
      Instructions for Epic Games Store are as follows:   <br/>
      Note: The Epic Games Store version of ARK does not currently have a proper method of joining a server directly via IP/port. This is not a limitation on our part.   <br/>
      <br/>
      Step 1: Join a single-player game of ARK.   <br/>
      Step 2: Click Tab to open the console.   <br/>
      Step 3: Enter server ip below in the format of IP:PORT.   <br/>
      Step 3: Type: open SERVERIP:PORT and press enter.   <br/>
    </p>
		<div class="justify-center items-center space-y-4 sm:flex sm:space-y-0 sm:space-x-4 hidden">
			<a href="#"
				class="w-full sm:w-auto hidden bg-gray-800 hover:bg-gray-700 focus:ring-4 focus:ring-gray-300 text-white rounded-lg inline-flex items-center justify-center px-4 py-2.5 dark:bg-gray-700 dark:hover:bg-gray-600 dark:focus:ring-gray-700">
                <i class="fa-solid fa-circle-question text-2xl mr-3"></i>
				<div class="text-left">
					<div class="font-sans text-sm font-semibold">Joining Guide</div>
				</div>
			</a>
		</div>
          </div>
          <div class="flex-initial w-3/4">
            <div class="p-2 px-5 w-full bg-bgray-secondary mb-10 rounded-2xl flex">
            <input type="email" name="email" id="email" class="w-1/4 bg-bgray-secondary border border-gray-700 text-white rounded-full focus:ring-blue-500 focus:border-blue-500 block p-2.5 " placeholder="Search for servers" required=""/>
            <button class="mb-2 md:mb-0 bg-bgray-secondary ring-1 ring-bgray-forward px-4 py-2 shadow-sm font-semibold text-gray-100 rounded-full inline-flex items-center space-x-2 ml-2"><div class="flex"><span>Downtime - 0 Players Online </span><i class="fa-solid fa-circle text-red-500 animate-pulse my-auto ml-2"></i></div></button>
            </div>
            <div class="grid mt-8  gap-8 grid-cols-1 md:grid-cols-2 xl:grid-cols-2">
              <ServerCard/>
              <ServerCard/>
              <ServerCard/>
              <ServerCard/>
              <ServerCard/>
              <ServerCard/>
              <ServerCard/>
              <ServerCard/>
              <ServerCard/>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

export async function getServerSideProps() {
  console.log("[ShadowmaneAPI] DEBUG: Fetched Server List Options");

  const res = await fetch(
    "http://bloody-ark.com:3000/api/options/serverlist_options"
  );

  var serverlist_options = null;
  try {
    serverlist_options = await res.json();
  } catch (e) {
    console.error("[ShadowmaneAPI] ERROR: Failed to set options");
  }

  return {
    props: {
      serverlist_options,
    },
  };
}

export default ServerList;
